site_name: FastAPI Sample Docs
nav:
  - Home: index.md
  - Install: install.md
  - Demos: demos.md
  - Features: features.md
  - Settings: settings.md
  - Logging: logging.md
  - ErrorExceptions: errors.md
  - Testing: testing.md
  - Migration: migration.md
  - CI/CD: ci-cd.md
  - PackageManagement: package-management.md
  - CRUD: crud.md
  - Models: models.md
  - Endpoints: endpoints.md
  - Schemas: schemas.md
  - PermissionScopes: permission-scopes.md
  - Docker: docker.md
  - Deployment: deployment.md
